### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bbalban** [ForestAdmin/lumber#167]
it looks awesome except I had a few showstopper issues:

1. I strongly prefer to run it locally instead of through an insecure http app.forestadmin.com. It's the entire database of my application, I would prefer to run it locally.

2. I saw an issue with NodeJS and PostgreSQL/Sequelize: 
```Unexpected error: column CommentActions.created_at does not exist```

I pretty much had the same error for all tables I tried to access.

I'll probably not use this due to issue (1)

**Comment by SeyZ** [comment]
Hey @bbalban Thanks for the feedback.

1. You can configure SSL on your lumber-generated project using a web server proxy_pass, or a tunnel using a tool like ngrok or with another solution. If your node app is configured with SSL, app.forestadmin.com will enforce HTTPS automatically. You can read more about this here: https://doc.forestadmin.com/knowledge-base.html#https-and-mixed-content-risks

2. This is definitively a bug. I will try to reproduce it. As a quick work around, you can add the Sequelize option `timestamps: false` to your models because your tables don't have the created_at / updated_at field.
