### ISSUE TITLE
Server does not support SSL connections on remote db

### ISSUE THREAD

**Issue by benlienart** [ForestAdmin/lumber#193]
Hi,

I am trying to install lumber with a remote db instance on Heroku. Here's my config : 
```
? What's the database type?  postgres
? What's the database name? [db name]
? What's the database schema? [optional] public
? What's the database hostname? [ec2 instance name].eu-west-1.compute.amazonaws.com
? What's the database port? 5432
? What's the database user?  [db user name]
? What's the database password? [optional]  [hidden]
? Does your database require a SSL connection?  Yes
? What's the IP/hostname on which your back office will be running?  localhost
? What's the port on which your back office will be running?  4000
```

I get `👍  Hooray, installation success! 👍`, the db models are discovered ok, but when logging on the UI, i get a `Oops, something went wrong`error when trying to visualize the data, and get the following error on the terminal :

```
[forest] 🌳🌳🌳  Unexpected error: The server does not support SSL connections
SequelizeConnectionError: The server does not support SSL connections
```

Could you help me figure out what's wrong here ? Thanks !

**Comment by SeyZ** [comment]
Hi @benlienart 

This error is thrown by the Sequelize ORM, which is responsible to manage the connection to your database hosted on EC2.

My guess here is that you answered to the question "? Does your database require a SSL connection?" -> yes.

Are you sure about this? Because the error said: The server does not support SSL connections

Can you confirm you really require a database SSL connection? Let me know, thanks!

**Comment by benlienart** [comment]
Hi @SeyZ ,

I indeed answered `? Does your database require a SSL connection? Yes`. Otherwise connection to the db fails at the `lumber generate` stage.

Futhermore, i checked that the remote db requires SSL connection by logging successfully to the db by the following command :
`psql -u [db_user] "sslmode=require host=[db_host] dbname=[db_name]"`

Best regards

**Comment by AlexandreIsMe** [comment]
Hi @SeyZ !

I've got a similar issue, with the same configuration. I am running a db on heroku postgres. I cannot install `lumber-forestadmin`. The error I get is:

```
Cannot connect to the database due to the following error:
> SequelizeConnectionError: no pg_hba.conf entry for host [host], user [username], database [database_name], SSL off
```

I think my issue is because lumber is trying to connect with `SSL` set to `off`. However, I answered yes to `Does your database require a SSL connection?` and I've checked in the .env file, where SSL seems to be enabled. I do not see any mistake in the `DATABASE_URL` value.

@benlienart could you manage to make this work?

Best regards

**Comment by RadoRado** [comment]
I have the same issue.

Tried connecting to a local Postgres & to a Postgres running on Heroku.

And then, when I run:

```
lumber install lumber-forestadmin --email <email> --projectName <email>
```

I get the following error:

```
> Cannot connect to the database due to the following error:
> SequelizeConnectionError: no pg_hba.conf entry for host "94.155.19.8", user "wtwlatqprzyszi", database "dd392qots70t0m", SSL off
```

**Comment by Ninoks** [comment]
Following ! 
Same here, running Postgres on Heroku.

**Comment by RadoRado** [comment]
Updating to `lumber-cli@2.1.0` solved the issue for me :+1:

**Comment by VincentMolinie** [comment]
@JeanCarrot `lumber-cli@2.1.0` should fix your issue

**Comment by VincentMolinie** [comment]
@benlienart does it fix your issue ?

**Comment by VincentMolinie** [comment]
I close this issue as it should be fix by last version of lumber

**Comment by chrisbag** [comment]
Hello,
I am getting the same issue with lumber@3.6.11 connecting to postgres on Heroku

` Cannot connect to the database due to the following error:
> SequelizeConnectionError: no pg_hba.conf entry for host "94.155.19.8", user "wtwlatqprzyszi", database "dd392qots70t0m", SSL off`

**Comment by EvanPHamilton** [comment]
Am getting this issue as well

**Comment by bloudermilk** [comment]
In my case I had two problems that caused the same error as @chrisbag and @RadoRado:

1. Forgetting to set `DATABASE_SSL=true` in Heroku
2. Needing to set `DATABASE_REJECT_UNAUTHORIZED=false` to overcome [this bug](https://stackoverflow.com/a/61350416/29297)

Once I set those everything worked fine.
