### ISSUE TITLE
Install gives a blank page

### ISSUE THREAD

**Issue by cosmith** [ForestAdmin/lumber#220]
Hi, I tried following the instructions to test forest admin on my app, but had several issues...

- `lumber login` doesn't do anything 
- when I launch `yarn start` in the generated app, I get this:
![image](https://user-images.githubusercontent.com/1194749/57137265-9fd8ca00-6daf-11e9-8697-940d71c068c3.png)

I also tried adding the `lumber-forestadmin` plugin but it didn't change anything.

I'm confused...

**Comment by SeyZ** [comment]
Hey @cosmith After adding the `lumber-forestadmin` plugin, can you see it under the "Installed middlewares" ?

**Comment by vessenes** [comment]
I have the same problem. Ubuntu 18.04. npm 3.5.2, node 8.10.0

I used `npm install lumber-forestadmin` and got this:

```
$ npm install lumber-forestadmin
<snip>
├─┬ debug@4.0.1
│ └── ms@2.1.1
├─┬ express@4.16.4
│ ├─┬ body-parser@1.18.3
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ └── http-errors@1.6.3
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├─┬ finalhandler@1.1.1
│ │ └─┬ debug@2.6.9
│ │   └── ms@2.0.0
│ └─┬ send@0.16.2
│   ├── debug@2.6.9
│   └── ms@2.0.0
├── lumber-forestadmin@1.0.3  extraneous
└─┬ sequelize@5.7.6
  ├── debug@4.1.1
  └── semver@5.7.0
```

**Comment by j1mmie** [comment]
I believe you have to follow that up with a `lumber install lumber-forestadmin`

Ran into this myself, did not find it in any of the documentation

**Comment by dylanhusted** [comment]
I had the same issue and just figured it out. What you're seeing is actually expected - it's your back office app at localhost:3000 (or whatever port you specified in setup). That's not the admin panel URL.

I'm sure there is a better order of operations (reading now, it seems very redundant), but here is what worked for me:

After creating your app and running npm install, you need to install lumber-forestadmin from npm:

npm install --save lumber-forestadmin

 Then, you need to sign in to forest, because `lumber login` failed for you as it did for me:

`lumber run lumber-forestadmin:login`

Thanks for pointing me in the right direction there @j1mmie (your command led me to that one).

Finally, I needed to run this command with my Forest account email as a param:

`lumber install lumber-forestadmin --email [YOUR-FOREST-EMAIL]`

No brackets of course. I found that command here: https://github.com/ForestAdmin/lumber/issues/224

After running that, I received the following output:

`Forest Admin Installation`

 `Create your admin panel:`
 `Hooray, installation success!`

 `Your admin panel is available here: `https://app.forestadmin.com/[ID]`

That link in the output is your Forest admin panel, not localhost:3000.

**Final Note:**

If you specified a custom port in your lumber generate command, your Forest panel will fail to connect. It queries localhost:3000 by default. So, you need to set your localhost forest app to 3000, get in the panel, and then update after successfully connecting and logging in to your custom port number.

This was pretty crazy. Forest team, please update your docs.

**Comment by marcperrinp** [comment]
Hi,

Apologies if this wasn't straight-forward!

Our **installation walkthroughs** are documented [here](https://docs.forestadmin.com/documentation/getting-started/installation/install-in-lumber) (note that we are still finetuning our Docker installation, so there might still be blocking points in some cases).

Feel free to reopen this issue if you encounter other installation issues.
