### ISSUE TITLE
Update Sequelize to v5.18.4 and to tedious v6.4.0 to make MSSQL work 

### ISSUE THREAD

**Issue by rasmusfjord** [ForestAdmin/lumber#257]
## Expected behavior
Being able to use firestadmin with MSSQL

## Actual behavior
Couldnt, threw 2 errors. 
`encrypt needs to set to true` and  `Cant login with ''`

## Failure Logs
Nothing

## Context
This was when the admin panel on your end tried to talk through the node app installed on our end. 

* Lumber Package Version:1.2.1
* Database Dialect: MSSQL
* Database Version: x

To make it work, or at least get closer, update these 2 packages:
   "sequelize": 5.18.4
    "tedious": ": 6.4.0

**Comment by rap2hpoutre** [comment]
Hi @rasmusfjord! Thank you for your contribution! (sorry for late answer)

The issue you mentioned about MSSQL may have been fixed in Lumber v1.5.1 (see [this commit](https://github.com/ForestAdmin/lumber/commit/30081f4908b7bcd6960802c65786f78a3d129280)). 

Update Lumber to latest version (e.g `npm i -g lumber-cli@latest`) then try to generate your backend again. Let me know if it fix your issue!

**Comment by rap2hpoutre** [comment]
@rasmusfjord Is your issue fixed?

**Comment by rap2hpoutre** [comment]
I guess this is fixed now. Feel free to re-open this issue if the problem persists after lumber upgrade.
