### ISSUE TITLE
Model creation error and unable to access application

### ISSUE THREAD

**Issue by JustJasper** [ForestAdmin/lumber#31]
Following successful installation, I get the following error when running the node ./bin/www command:

`user@domain:~$ cd "ExpertC" && node ./bin/www`
`Model creation error: SyntaxError: Unexpected token *`
`🌳  Open your admin UI: http://app.forestadmin.com 🌳`

While the final message appears to indicate success, it the ssh locks and I'm forced to Ctrl+C.   

Running `curl -I http://localhost:3000/forest` also appears to indicate that the server isn't running:

`user@domain:~/ExpertC$ curl -I http://localhost:3000/forest`
`curl: (7) Failed to connect to localhost port 3000: Connection refused`

Any help gratefully appreciated.  I did run into some memory issues on the original install, but having added a swap file to server, that appears to have been fixed.  Is it possible I'm encountering more memory-related issues here?

**Comment by SeyZ** [comment]
Hey @JustJasper Can you tell me the version of `node` installed?

**Comment by JustJasper** [comment]
Hi @SeyZ, I'm running Node 4.2.6 on Ubuntu 16.04.

**Comment by SeyZ** [comment]
Hey @JustJasper It seems one of our generates model in the `models` directory has a syntax error :( Do you know which one?

**Comment by JustJasper** [comment]
Ah, that makes sense - I had a depreciated table in my database which had asterisks in the field name (poor form, I know).  Have corrected that (removed the offending fields from the table), and no longer get the 'model creation error', however still unable to connect (server doesn't appear to be running) even after rerunning the `node ./bin/www` command. (my SSH connection also hangs at this point).

Apologies if I'm doing something stupid - I'm fairly new at this!

**Comment by SeyZ** [comment]
Hey @JustJasper what do you mean by 'My SSH connection also hangs at this point` ?

**Comment by JustJasper** [comment]
Apologies if unclear - when I run the `node ./bin/www` command, I get the `🌳 Open your admin UI: http://app.forestadmin.com 🌳` message, however, the process appears to 'hang' and I'm forced to Ctrl+C to get back to my command line prompt.

**Comment by Tapppi** [comment]
@JustJasper the "hang" you are describing is the actual express server just running and waiting for connections. If you open another terminal on the same machine after leaving the node server on and curl `http://localhost:3000` you will get connected, but probably encounter a `404` as lumber doesn't serve anything in root by default.

To use the dashboard, open the link given by the command (`http://app.forestadmin.com`) and login to see the project you created and connect to it. To connect you will need to configure access to the node server running. This will be dependant on your network. If you had the server running on localhost, it would be as easy as pointing the dashboard to `http://localhost:3000`, but since you seem to be running on a VPS of some sort, you will probably need to open a port to the liana (the server generated by lumber that servers data to your admin interface) and connect to it by ip or url (if you have a dns entry pointing to the ip of the VPS), e.g. `http://my-vps.my-domain.com:3000` or something.
