### ISSUE TITLE
Where are the REST docs?

### ISSUE THREAD

**Issue by MartinMuzatko** [ForestAdmin/lumber#40]
I read that Lumber/Forestadmin can be used to serve as a REST API for my database.

> Lumber generates a lightweight web app serving a REST API hooked directly into your database, so it works out-of-the-box for MySQL and Postgres.

When browsing the tables, I get some calls in the terminal - Yes. But how do I know how to access these via my app?
There is no url provided.

Is it localhost/forest/content/65565 ? Is there no port?
Is it http://app.forestadmin.com/forest/content/65565?
None of them work.

It would be nice to have some more information on how to actually use forestadmin together with lumber, in order to have a REST API.

**Comment by alexparker** [comment]
http://doc.forestadmin.com/api-reference/

**Comment by MartinMuzatko** [comment]
This does not work for me @alexparker
If I run this locally, http://localhost/forest/content/65565 returns "this site can't be reached"
It would be nice to know how to access this on localhosts. Again: I don't think that lumber hosts on port 80 for localhost. But there is no message either.. Any ideas?

**Comment by alexparker** [comment]
Lumber runs a small express server if you open the folder it creates, which by default runs on port 3000. 

And it uses jsonapi specification I believe. which has a pretty strict standard to it. 

On Thu, Dec 08, 2016 at 7:34 AM Martin Muzatko

<
mailto:Martin Muzatko <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

This does not work for me
https://github.com/alexparker
If I run this locally,
http://localhost/forest/content/65565
returns "this site can't be reached"

It would be nice to know how to access this on localhosts. Again: I don't think that lumber hosts on port 80 for localhost. But there is no message either.. Any ideas?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ForestAdmin/lumber/issues/40#issuecomment-265753877
, or

**Comment by MartinMuzatko** [comment]
Awesome! that works for me. You really need to document the default port when running locally for development. This tool is starting to make sense. :)

Thank you a lot for your time.

**Comment by alexparker** [comment]
I'm not part of forest :) just a fellow developer interested in using it too 😜 and helping out where I can.

You could make a PR on the readme if you wanted to help out too. 

On Thu, Dec 08, 2016 at 8:38 AM Martin Muzatko

<
mailto:Martin Muzatko <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Awesome! that works for me. You really need to document the default port when running locally for development. This tool is starting to make sense. :)

Thank you a lot for your time.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ForestAdmin/lumber/issues/40#issuecomment-265770658
, or

**Comment by SeyZ** [comment]
Hey @MartinMuzatko thank you for your question, you're right it's not enough clear!
@alexparker You rock man, thanks for your contribution on this issue :D

I close the issue, PR are more than welcome to improve our README/Code 👍
