### ISSUE TITLE
Delay the Forest account/project creation process until after the database metadata is read

### ISSUE THREAD

**Issue by emir-harbinja** [ForestAdmin/lumber#43]
In order to prevent the creation of redundant projects and multiple Forest accounts, the interaction with the Forest API should be delayed until after the database metadata is successfully read.

**Comment by SeyZ** [comment]
Hey @emir-harbinja 

Not sure to understand the flow you described. Can you explain me how I can reproduce the problem?

Thanks!!

**Comment by emir-harbinja** [comment]
@SeyZ 
Here is one way to reproduce the problem:
1. create a folder 'abc' in the current directory
2. run lumber CLI
3. set project name to 'abc'
4. enter new Forest credentials

The CLI should fail telling you that the folder already exists but the Forest account will be created.

Another way to encounter this issue is by reproducing issue #5. Both the Forest account and Forest project will be created, but no application will be generated. The next attempt will generate a duplicate project name on Forest.

**Comment by arnaudbesnier** [comment]
Hi @emir-harbinja,

As this ticket is pretty old and lumber evolved a lot in 3 years, I am pretty sure this issue is fixed now on Lumber CLI v3.3.3.
One of the first potential errors raised in the process is that the folder with the project name entered already exists in the current location.

Let me close this discussion, but feel free to reopen it if you still experience such issue using the latest Lumber version.

🌲🌲🌲
