### ISSUE TITLE
CRUD on mongoose dataBase with deepObject display "[Object, Object]"

### ISSUE THREAD

**Issue by c0ncentus** [ForestAdmin/lumber#463]
## Expected behavior
![image](https://user-images.githubusercontent.com/25374826/92326308-67a36480-f051-11ea-9564-5bdac13891dc.png)
When we click it, 
display a JSON view 
and then possibility to edit this.

## Actual behavior
my object on the database

![image](https://user-images.githubusercontent.com/25374826/92326236-0b404500-f051-11ea-9571-1b977971556d.png)

## Failure Logs
.

## Context

Basic setup with my localhost database

* Lumber Package Version: 3.6.8
* Database Dialect: Mongodb
* Database Version:
    "forest-express": "^7.4.0",
    "forest-express-mongoose": "^6.0.0",
    "mongoose": "~5.8.2"

**Comment by rap2hpoutre** [comment]
Hi @c0ncentus Thank you for your feedback. I'm not sure this issue is related to lumber itself but it's a problem with Forest Admin, so I suggest you open an issue on the community forum here: https://community.forestadmin.com/

Could you please open an issue on the [forum](https://community.forestadmin.com/)? (be sure you will have some feedback since there are dedicated people in charge of the answers each day).

**Comment by c0ncentus** [comment]
ok thanks
