### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'created_at' in 'field list'

### ISSUE THREAD

**Issue by icodejs** [ForestAdmin/lumber#49]
Hi Louis,

I successfully setup my admin and most tables worked fine but I had issues loading my tables that contained the fields `createdAt` and `updateAt`.

My console outputted the following error:

```
GET http://localhost:3000/forest/user?fields%5Buser%5D=id%2CisAdmin%2Cemail%2Cp…dated_at&page%5Bnumber%5D=1&page%5Bsize%5D=10&sort=-id&timezone=%2B00%3A00 400 (Bad Request)
vendor-89886a0….js:10 Error: Ember Data Request GET http://localhost:3000/forest/user returned a 400
Payload (application/json; charset=utf-8)
[object Object]
    at i.t (vendor-89886a0….js:10)
    at i (vendor-89886a0….js:25)
    at n.handleResponse (vendor-89886a0….js:25)
    at n.handleResponse (client-d59da52….js:33)
    at n [as handleResponse] (vendor-89886a0….js:11)
    at n.c.error (vendor-89886a0….js:25)
    at u (vendor-89886a0….js:3)
    at Object.fireWith [as rejectWith] (vendor-89886a0….js:3)
    at r (vendor-89886a0….js:4)
    at XMLHttpRequest.<anonymous> (vendor-89886a0….js:5)
```

With a network response of:
```json
{
  "errors": [{
    "detail": "ER_BAD_FIELD_ERROR: Unknown column 'created_at' in 'field list'"
  }]
}
```

I also inspected my terminal output and saw:
```shell
[forest] 🌳🌳🌳  ER_BAD_FIELD_ERROR: Unknown column 'created_at' in 'field list'
```

I went into my database and added a new column called `created_at` (and `updated_at`, as this caused the same issue) then everything worked fine.

I'm a bit confused as to why the admin is looking for this field.

Let me know your thoughts.

Cheers,
Tahir

**Comment by SeyZ** [comment]
Hey @icodejs 

Sequelize expects by default these timestamp fields. Lumber has a function (https://github.com/ForestAdmin/lumber/blob/master/services/dumper.js#L20) to detect if the table have `createdAt` or `updatedAt` fields and configure the Sequelize option (`timestamps`) in the model definition.

In your case, it seems that the analyze didn't work well. According to the sequelize documentation (http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration), you can configure your field timestamps something like:

```
'use strict';

module.exports = (sequelize, DataTypes) => {
  let models = sequelize.models;

  var Model = sequelize.define('your_model_name', {
    // ...
  }, {
    classMethods: {
      associate: () => {
        // ...
      }
    },
    tableName: 'your_table_name',
    timestamps: true,
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  });

  return Model;
};
```

I think you have the option `underscored: true`, so Sequelize tries to resolve the timestamp fields ith `created_at` instead of `createdAt`. So you can force the name to use with my options above.

Am I right? Let me know :)

**Comment by icodejs** [comment]
Hi @SeyZ,

Updating the model options to `underscored: false` solved my issue.

Thank you very much.

Where is the best place to ask general questions that aren't bugs or issues?

Tahir

**Comment by icodejs** [comment]
FYI!

I had to disable Github 2-factor authentication in order to successfully deploy via `lumber heroku-deploy -c`.

You may want to update your documentation / test this out for yourself.

;)
