### ISSUE TITLE
Problem while getting id of selected items with custom actions

### ISSUE THREAD

**Issue by KevinL59** [ForestAdmin/lumber#85]
Hi everybody,

I have an issue when i trying to reach ids of selected items of an actions.

I selected for exemple two items : 
<img width="694" alt="ids_capture" src="https://user-images.githubusercontent.com/14981739/27087752-285068da-5056-11e7-8f75-8941619bd6f9.PNG">

I click on my action button and the ids of my item are send to my lumber back-end on an heroku instance.

I used :
```javascript
router.post('/actions/my-custom-action', liana.ensureAuthenticated,
  (req, res) => {
    console.log(req.body['data']['attributes']['ids'])
    res.send({
      success: 'It works!'
    });
  }
);
```
to print the ids of the items I receive and the result is really weird :
<img width="641" alt="ids_capture_2" src="https://user-images.githubusercontent.com/14981739/27088469-022badde-5058-11e7-8863-dbe00916d5ff.PNG">

Is it normal that the three uuid of my object (one is the key id and the two other are foreign key) are in the same string ? 
I don't know if the error come from my side or not...

Thanks for your help.

**Comment by arnaudbesnier** [comment]
Hi @KevinL59,

The issue definitely comes from Lumber.
I guess that the model declaration in your generated application have several attributes that contain the `primaryKey: true` option.

Lumber has some know issues on primary keys detections, so what you have to do to fix this manually is to edit your models (in the code) and delete the `primaryKey: true` options for columns that are not a primary key in your database.

Note: With your current configuration, the collection with your Smart Action is considered as a table with a composite primary key. That's why the ids send are the concatenation of several columns values.

**Comment by arnaudbesnier** [comment]
@KevinL59, Please reopen this issue if it didn't help.

Thanks
